console.log("Hello Winc Academy");
let name = "Judith";
console.log(name);
let sum = 4 + 4;
console.log("sum", sum);
let addString = "4" + "4";
console.log("addString", addString);
let testAddition = 1 + 1;
console.log("addition", testAddition);
let testSubstraction = 7 - 1;
console.log("substraction", testSubstraction);
let testMultiplication = 3 * 3;
console.log("multiplication", testMultiplication);
let testDivision = 10 / 2;
console.log("division", testDivision);
let testModulus = 10 % 2;
console.log("modulus", testModulus);
let age = 44;
console.log("typeof age", age);
let nwAge = "44";
console.log("typeof nwAge", nwAge);
